-- MySQL Script generated by MySQL Workbench
-- Fri Sep 10 19:51:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `cedulaUsuario` VARCHAR(20) NOT NULL,
  `generoUsuario` VARCHAR(45) NOT NULL,
  `rolUsuario` VARCHAR(45) NOT NULL,
  `contrasenaUsuario` VARCHAR(45) NOT NULL,
  `emailUsuario` VARCHAR(45) NOT NULL,
  `celularUsuario` VARCHAR(45) NOT NULL,
  `direccionUsuario` VARCHAR(45) NOT NULL,
  `codigoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `codigoUsuario_UNIQUE` (`codigoUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plazas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plazas` (
  `idPlaza` INT NOT NULL AUTO_INCREMENT,
  `nombrePlaza` VARCHAR(45) NOT NULL,
  `estadoPlaza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlaza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InformacionEmpresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InformacionEmpresa` (
  `idInformacionEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nitEmpresa` VARCHAR(30) NOT NULL,
  `nombreEmpresa` VARCHAR(45) NOT NULL,
  `direccionEmpresa` VARCHAR(45) NOT NULL,
  `valorMinuto` VARCHAR(45) NOT NULL,
  `ivaActual` DOUBLE NULL,
  PRIMARY KEY (`idInformacionEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registro` (
  `idRegistro` INT NOT NULL AUTO_INCREMENT,
  `placaVehiculo` VARCHAR(45) NOT NULL,
  `fechaEntrada` DATETIME NOT NULL,
  `fechaSalida` DATETIME NULL,
  `idUsuario` INT NOT NULL,
  `idPlaza` INT NOT NULL,
  `fechaFactura` DATE NULL,
  `nombreCliente` VARCHAR(45) NULL,
  `minutosTotales` INT NULL,
  `iva` DOUBLE NULL,
  `totalCancelar` DOUBLE NULL,
  `idInformacionEmpresa` INT NOT NULL,
  PRIMARY KEY (`idRegistro`),
  INDEX `registroUsuarios_idx` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `idRegistro_UNIQUE` (`idRegistro` ASC) VISIBLE,
  INDEX `plazaRegistro_idx` (`idPlaza` ASC) VISIBLE,
  INDEX `informacionEmpresaRegistro_idx` (`idInformacionEmpresa` ASC) VISIBLE,
  CONSTRAINT `registroUsuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `plazaRegistro`
    FOREIGN KEY (`idPlaza`)
    REFERENCES `mydb`.`Plazas` (`idPlaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `informacionEmpresaRegistro`
    FOREIGN KEY (`idInformacionEmpresa`)
    REFERENCES `mydb`.`InformacionEmpresa` (`idInformacionEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
