-- MySQL Script generated by MySQL Workbench
-- Tue Sep 21 20:20:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema easyparkingdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easyparkingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easyparkingdb` DEFAULT CHARACTER SET utf8 ;
USE `easyparkingdb` ;

-- -----------------------------------------------------
-- Table `easyparkingdb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyparkingdb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `apellidoUsuario` VARCHAR(45) NOT NULL,
  `cedulaUsuario` VARCHAR(45) NOT NULL,
  `generoUsuario` VARCHAR(45) NOT NULL,
  `rolUsuario` VARCHAR(45) NOT NULL,
  `contrasenaUsuario` VARCHAR(45) NOT NULL,
  `emailUsuario` VARCHAR(45) NOT NULL,
  `celularUsuario` VARCHAR(45) NOT NULL,
  `direccionUsuario` VARCHAR(45) NOT NULL,
  `codigoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuarios_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `cedulaUsuario_UNIQUE` (`cedulaUsuario` ASC) VISIBLE,
  UNIQUE INDEX `contrasenaUsuario_UNIQUE` (`contrasenaUsuario` ASC) VISIBLE,
  UNIQUE INDEX `codigoUsuario_UNIQUE` (`codigoUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyparkingdb`.`Plaza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyparkingdb`.`Plaza` (
  `idPlaza` INT NOT NULL,
  `nombrePlaza` VARCHAR(45) NOT NULL,
  `estadoPlaza` VARCHAR(45) NOT NULL,
  `tipoPlaza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlaza`),
  UNIQUE INDEX `idPlaza_UNIQUE` (`idPlaza` ASC) VISIBLE,
  UNIQUE INDEX `nombrePlaza_UNIQUE` (`nombrePlaza` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyparkingdb`.`InformacionEmpresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyparkingdb`.`InformacionEmpresa` (
  `idInformacionEmpresa` INT NOT NULL,
  `nitEmpresa` VARCHAR(45) NOT NULL,
  `nombreEmpresa` VARCHAR(45) NOT NULL,
  `direccionEmpresa` VARCHAR(45) NOT NULL,
  `valorMinutoCarro` VARCHAR(45) NOT NULL,
  `valorMinutoMoto` VARCHAR(45) NOT NULL,
  `ivaActual` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInformacionEmpresa`),
  UNIQUE INDEX `idInformacionEmpresa_UNIQUE` (`idInformacionEmpresa` ASC) VISIBLE,
  UNIQUE INDEX `nitEmpresa_UNIQUE` (`nitEmpresa` ASC) VISIBLE,
  UNIQUE INDEX `nombreEmpresa_UNIQUE` (`nombreEmpresa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyparkingdb`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyparkingdb`.`Registro` (
  `idRegistro` INT NOT NULL,
  `placaVehiculo` VARCHAR(45) NOT NULL,
  `fechaEntrada` DATETIME(6) NULL,
  `fechaSalida` DATETIME(6) NULL,
  `fechaFactura` DATE NOT NULL,
  `nombreCliente` VARCHAR(45) NULL,
  `minutosTotales` INT NOT NULL,
  `iva` DOUBLE NOT NULL,
  `totalCancelar` DOUBLE NOT NULL,
  `idUsuario` INT NOT NULL,
  `idPlaza` INT NOT NULL,
  `idInformacionEmpresa` INT NOT NULL,
  PRIMARY KEY (`idRegistro`),
  UNIQUE INDEX `idRegistro_UNIQUE` (`idRegistro` ASC) VISIBLE,
  UNIQUE INDEX `idPlaza_UNIQUE` (`idPlaza` ASC) VISIBLE,
  INDEX `idUsuario_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `idInformacionEmpresa_idx` (`idInformacionEmpresa` ASC) VISIBLE,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `easyparkingdb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPlaza`
    FOREIGN KEY (`idPlaza`)
    REFERENCES `easyparkingdb`.`Plaza` (`idPlaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idInformacionEmpresa`
    FOREIGN KEY (`idInformacionEmpresa`)
    REFERENCES `easyparkingdb`.`InformacionEmpresa` (`idInformacionEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
